### ISSUE TITLE
Failed action

### ISSUE THREAD

**Issue by mcollina** [gigsboat/gigs-template#6]
In my top-recent push, the action failed:

```
Run github-actions-x/commit@v2.8
/usr/bin/docker run --name d7822dfbd8ff249269ea951f50fa511df_09ad04 --label 08450d --workdir /github/workspace --rm -e INPUT_GITHUB-TOKEN -e INPUT_PUSH-BRANCH -e INPUT_COMMIT-MESSAGE -e INPUT_FILES -e INPUT_NAME -e INPUT_EMAIL -e INPUT_FORCE-ADD -e INPUT_FORCE-PUSH -e INPUT_REBASE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/public-speaking/public-speaking":"/github/workspace" 08450d:7822dfbd8ff249269ea951f50fa511df
Traceback (most recent call last):
  File "/entrypoint.py", line 57, in <module>
    run()
  File "/entrypoint.py", line 51, in run
    debug(git(['checkout', '-B', branch]))
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 99, in __call__
    return self.run(args, **kwargs)[1]
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 240, in run
    return p.run()
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 201, in runner
    return run_proc(p, retcode, timeout)
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/processes.py", line 322, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/processes.py", line 24, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.7/site-packages/plumbum/machines/base.py", line 29, in verify
    getattr(self, "argv", None), self.returncode, stdout, stderr
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: [12](https://github.com/mcollina/public-speaking/runs/6367390568?check_suite_focus=true#step:7:12)8
Command line: | /usr/bin/git checkout -B main
Stderr:       | fatal: unsafe repository ('/github/workspace' is owned by someone else)
              | To add an exception for this directory, call:
              | 
              | 	git config --global --add safe.directory /github/workspace
login mcollina
password ***
machine api.github.com
login mcollina
password ***
```

https://github.com/mcollina/public-speaking/runs/6367390568?check_suite_focus=true

**Comment by lirantal** [comment]
Thanks! Forgot to update the template repository.
Fixed in https://github.com/gigsboat/gigs-template/commit/286a1edcb9a43329993dddb3b641d8adae2cda9f and also pushed a PR to your repository at https://github.com/mcollina/public-speaking/pull/1
